# Generated by Django 5.2.11 on 2026-02-19 23:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    """Force course_id to be case-insensitively unique"""

    dependencies = [
        ('split_modulestore_django', '0003_alter_historicalsplitmodulestorecourseindex_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='splitmodulestorecourseindex',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('course_id'), name='splitmodulestorecourseindex_courseid_unique_ci'),
        ),
    ]
